<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Saishanmuk" ignored="0" name="Test" tests="3" failures="1" timestamp="2021-03-01T18:57:46 IST" time="14.582" errors="0">
  <testcase name="webPageNavigation" time="6.981" classname="com.pratian.testclasses.AddFlightTest"/>
  <testcase name="signInuser" time="0.76" classname="com.pratian.testclasses.AddFlightTest"/>
  <testcase name="clickAddFlight" time="2.911" classname="com.pratian.testclasses.AddFlightTest">
    <failure type="java.lang.AssertionError" message="expected [Flight added successfuly] but found [Add Flight]">
      <![CDATA[java.lang.AssertionError: expected [Flight added successfuly] but found [Add Flight]
at com.pratian.testclasses.AddFlightTest.clickAddFlight(AddFlightTest.java:146)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- clickAddFlight -->
</testsuite> <!-- Test -->
